window.OP_SHOP_SEEDS = [
  {name:"Helping Hands Mission — Airport West",address:"14 McIntosh Street, Airport West VIC",suburb:"Airport West",postcode:"3042",operator:"Helping Hands Mission",source:"Official"},
  {name:"Helping Hands Mission — Sunshine",address:"85–89 Hampshire Road, Sunshine VIC",suburb:"Sunshine",postcode:"3020",operator:"Helping Hands Mission",source:"Official"},
  {name:"Helping Hands Mission — Preston",address:"66–68 Oakover Road, Preston VIC",suburb:"Preston",postcode:"3072",operator:"Helping Hands Mission",source:"Official"},
  {name:"Save the Children — Brunswick",address:"478 Sydney Road, Brunswick VIC",suburb:"Brunswick",postcode:"3056",operator:"Save the Children",source:"Official"},
  {name:"Save the Children — Dandenong",address:"1/119–123 Lonsdale Street, Dandenong VIC",suburb:"Dandenong",postcode:"3175",operator:"Save the Children",source:"Official"},
  {name:"Save the Children — Frankston",address:"7B Station Street, Frankston VIC",suburb:"Frankston",postcode:"3199",operator:"Save the Children",source:"Official"},
  {name:"Save the Children — Malvern",address:"181 Glenferrie Road, Malvern VIC",suburb:"Malvern",postcode:"3144",operator:"Save the Children",source:"Official"},
  {name:"Save the Children — Northcote",address:"292 High Street, Northcote VIC",suburb:"Northcote",postcode:"3070",operator:"Save the Children",source:"Official"},
  {name:"Save the Children — Windsor",address:"59–61 Chapel Street, Windsor VIC",suburb:"Windsor",postcode:"3181",operator:"Save the Children",source:"Official"},
  {name:"Sacred Heart Mission — Bentleigh",address:"271 Centre Road, Bentleigh VIC",suburb:"Bentleigh",postcode:"3204",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — Brighton",address:"361 Bay Street, Brighton VIC",suburb:"Brighton",postcode:"3186",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — Cheltenham",address:"261 Charman Road, Cheltenham VIC",suburb:"Cheltenham",postcode:"3192",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — Coburg",address:"297–301 Sydney Road, Coburg VIC",suburb:"Coburg",postcode:"3058",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — Hawthorn",address:"86 Riversdale Road, Hawthorn VIC",suburb:"Hawthorn",postcode:"3122",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — Northcote",address:"387 High Street, Northcote VIC",suburb:"Northcote",postcode:"3070",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — Prahran Chapel St",address:"262 Chapel Street, Prahran VIC",suburb:"Prahran",postcode:"3181",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — Prahran Commercial Rd",address:"110 Commercial Road, Prahran VIC",suburb:"Prahran",postcode:"3181",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — Preston",address:"311 High Street, Preston VIC",suburb:"Preston",postcode:"3072",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — South Melbourne",address:"365 Clarendon Street, South Melbourne VIC",suburb:"South Melbourne",postcode:"3205",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Sacred Heart Mission — St Kilda",address:"87A Grey Street, St Kilda VIC",suburb:"St Kilda",postcode:"3182",operator:"Sacred Heart Mission",source:"Official"},
  {name:"Red Cross Shop — Port Melbourne",address:"231 Bay Street, Port Melbourne VIC",suburb:"Port Melbourne",postcode:"3207",operator:"Australian Red Cross",source:"Official"},
  {name:"Salvos Stores — Brunswick",address:"740 Sydney Road, Brunswick VIC",suburb:"Brunswick",postcode:"3056",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Bundoora",address:"1/89 Plenty Road, Bundoora VIC",suburb:"Bundoora",postcode:"3083",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Carlton",address:"747 Nicholson Street, Carlton VIC",suburb:"Carlton",postcode:"3053",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Carnegie",address:"154 Koornang Road, Carnegie VIC",suburb:"Carnegie",postcode:"3163",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Castlemaine",address:"46 Forest Street, Castlemaine VIC",suburb:"Castlemaine",postcode:"3450",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Chelsea",address:"407 Nepean Highway, Chelsea VIC",suburb:"Chelsea",postcode:"3196",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Chelsea Heights",address:"2/1–5 Hartwood Crescent, Chelsea Heights VIC",suburb:"Chelsea Heights",postcode:"3196",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Cheltenham",address:"1216 Nepean Highway, Cheltenham VIC",suburb:"Cheltenham",postcode:"3192",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Craigieburn",address:"2/25 Interlink Drive, Craigieburn VIC",suburb:"Craigieburn",postcode:"3064",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Cranbourne North",address:"10A/350 Gippsland Highway, Cranbourne North VIC",suburb:"Cranbourne North",postcode:"3977",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Dandenong",address:"1/111–115 Lonsdale Street, Dandenong VIC",suburb:"Dandenong",postcode:"3175",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Epsom",address:"182–192 Midland Highway, Epsom VIC",suburb:"Epsom",postcode:"3551",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Fairfield",address:"300 Station Street, Fairfield VIC",suburb:"Fairfield",postcode:"3078",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Fawkner",address:"1323 Sydney Road, Fawkner VIC",suburb:"Fawkner",postcode:"3060",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Ferntree Gully",address:"1841–1843 Ferntree Gully Road, Ferntree Gully VIC",suburb:"Ferntree Gully",postcode:"3156",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Fitzroy",address:"427 Smith Street, Fitzroy VIC",suburb:"Fitzroy",postcode:"3065",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Forest Hill",address:"Shop MM05, 320 Canterbury Road, Forest Hill VIC",suburb:"Forest Hill",postcode:"3131",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Frankston",address:"17 Thompson Street, Frankston VIC",suburb:"Frankston",postcode:"3199",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Rowville",address:"Showroom 3/5 Fulham Road, Rowville VIC",suburb:"Rowville",postcode:"3178",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Roxburgh Park",address:"20 David Munroe Drive, Roxburgh Park VIC",suburb:"Roxburgh Park",postcode:"3064",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Sale",address:"221 Raymond Street, Sale VIC",suburb:"Sale",postcode:"3850",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Somerville",address:"Shop 32/17 Eramosa Road West, Somerville VIC",suburb:"Somerville",postcode:"3912",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — South Melbourne",address:"183 Clarendon Street, South Melbourne VIC",suburb:"South Melbourne",postcode:"3205",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — South Morang",address:"2/336 McDonalds Road, South Morang VIC",suburb:"South Morang",postcode:"3752",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Southern Cross",address:"669 Bourke Street, Melbourne VIC",suburb:"Melbourne",postcode:"3000",operator:"Salvos Stores",source:"Official"},
  {name:"Salvos Stores — Springvale",address:"Shop 3/819–823 Princes Highway, Springvale VIC",suburb:"Springvale",postcode:"3171",operator:"Salvos Stores",source:"Official"},
  {name:"Vinnies — Brunswick",address:"107 Sydney Road, Brunswick VIC",suburb:"Brunswick",postcode:"3056",operator:"Vinnies",source:"Official / local index"}
].map((s,i)=>({...s,id:`seed-${i+1}`,layer:"opshop",lat:null,lon:null,opening_hours:"",website:"",wheelchair:"",osm:false}));
