from pathlib import Path

path = Path('app.js')
s = path.read_text(encoding='utf-8')

replacements = [
('''  let parkingMarker = null;\n  let routeIds = new Set();''', '''  let parkingMarker = null;\n  let locationMarker = null;\n  let routeIds = new Set();'''),
('''    $("locateBtn").addEventListener("click", locateUser);\n    $("syncBtn").addEventListener("click",()=>refreshOSM(true));''', '''    $("locateBtn").addEventListener("click", locateUser);\n    $("locationSearchBtn").addEventListener("click", geocodeLocationSearch);\n    $("locationSearch").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();geocodeLocationSearch();}});\n    $("syncBtn").addEventListener("click",()=>refreshOSM(true));'''),
('''    const review=structuredCloneSafe(existing);const categories=p.categories.filter(c=>c.mode==="always");\n    const ratedIds=new Set(Object.keys(review.ratings||{}));\n    p.categories.filter(c=>c.mode==="adhoc"&&ratedIds.has(c.id)).forEach(c=>{if(!categories.some(x=>x.id===c.id))categories.push(c);});''', '''    const review=structuredCloneSafe(existing);review.categoryNames=review.categoryNames||{};const categories=p.categories.filter(c=>c.mode==="always");\n    const ratedIds=new Set(Object.keys(review.ratings||{}));\n    p.categories.filter(c=>c.mode==="adhoc"&&ratedIds.has(c.id)).forEach(c=>{if(!categories.some(x=>x.id===c.id))categories.push(c);});\n    ratedIds.forEach(id=>{if(!categories.some(c=>c.id===id)&&!p.categories.some(c=>c.id===id)&&review.categoryNames[id]) categories.push({id,name:review.categoryNames[id],mode:"oneoff"});});'''),
('''      <div class="modal-section form-grid"><label>Visited<input id="visitedAt" type="date" value="${esc(review.visitedAt||todayLocal())}"></label><label>Shop status<select id="shopStatus"><option value="visited">Visited</option><option value="want">Want to go</option><option value="skip">Skip for now</option></select></label></div>''', '''      <div class="modal-section form-grid"><label>Visited<input id="visitedAt" type="date" value="${esc(review.visitedAt||todayLocal())}"></label><label>Shop status<select id="shopStatus"><option value="visited" ${review.status!=="want"&&review.status!=="skip"?"selected":""}>Visited</option><option value="want" ${review.status==="want"?"selected":""}>Want to go</option><option value="skip" ${review.status==="skip"?"selected":""}>Skip for now</option></select></label></div>'''),
('''      review.notes=body.querySelector("#reviewNotes").value.trim();review.tags=parseTags(tagsInput.value);review.visitedAt=body.querySelector("#visitedAt").value;review.updatedAt=new Date().toISOString();review.categoryNames=review.categoryNames||{};categories.forEach(c=>review.categoryNames[c.id]=c.name);p.reviews[shop.id]=review;saveState();$("modal").close();render();''', '''      review.notes=body.querySelector("#reviewNotes").value.trim();review.tags=parseTags(tagsInput.value);review.visitedAt=body.querySelector("#visitedAt").value;review.status=body.querySelector("#shopStatus").value;review.updatedAt=new Date().toISOString();review.categoryNames=review.categoryNames||{};categories.forEach(c=>review.categoryNames[c.id]=c.name);p.reviews[shop.id]=review;saveState();$("modal").close();render();'''),
('''  function locateUser(){\n    if(!navigator.geolocation){alert("Location is not available in this browser.");return;}\n    $("locateBtn").textContent="Locating…";navigator.geolocation.getCurrentPosition(pos=>{userLocation={lat:pos.coords.latitude,lon:pos.coords.longitude};$("locateBtn").textContent="✓ Location on";map.setView([userLocation.lat,userLocation.lon],13);if($("sortSelect").value==="distance")render();},()=>{$("locateBtn").textContent="◎ Use my location";alert("Location permission was not available.");},{enableHighAccuracy:false,timeout:10000,maximumAge:300000});\n  }''', '''  function setOrigin(lat,lon,label){\n    userLocation={lat,lon,label};\n    if(locationMarker) map.removeLayer(locationMarker);\n    locationMarker=L.circleMarker([lat,lon],{radius:8,weight:3,fillOpacity:.85}).addTo(map).bindPopup(`<strong>${esc(label||"Starting point")}</strong>`);\n    map.setView([lat,lon],14,{animate:false});\n    $("locationHint").textContent=label?`Starting near ${label}`:"Starting from your location";\n    $("sortSelect").value="distance";\n    render();\n    map.setView([lat,lon],14,{animate:false});\n  }\n\n  function locateUser(){\n    if(!navigator.geolocation){alert("Location is not available in this browser.");return;}\n    $("locateBtn").textContent="Locating…";\n    navigator.geolocation.getCurrentPosition(pos=>{\n      $("locateBtn").textContent="✓ Using my location";\n      setOrigin(pos.coords.latitude,pos.coords.longitude,"your location");\n    },()=>{$("locateBtn").textContent="◎ Use my location";alert("Location permission was not available. You can type a suburb, street or postcode instead.");},{enableHighAccuracy:false,timeout:10000,maximumAge:300000});\n  }\n\n  async function geocodeLocationSearch(){\n    const input=$("locationSearch");const q=input.value.trim();if(!q)return;\n    const btn=$("locationSearchBtn");btn.disabled=true;btn.textContent="Finding…";$("locationHint").textContent="Looking for that place…";\n    try{\n      const query=/victoria|\\bvic\\b|australia/i.test(q)?q:`${q}, Victoria, Australia`;\n      const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=au&limit=5&addressdetails=1&q=${encodeURIComponent(query)}`;\n      const res=await fetch(url,{headers:{"Accept":"application/json"}});if(!res.ok)throw new Error(`Geocoder ${res.status}`);\n      const rows=await res.json();const hit=rows.find(r=>/Victoria/i.test(r.display_name||""))||rows[0];\n      if(!hit){$("locationHint").textContent="Couldn’t find that place. Try a suburb plus postcode.";return;}\n      const label=(hit.display_name||q).split(",").slice(0,3).join(",");setOrigin(Number(hit.lat),Number(hit.lon),label);\n    }catch(e){$("locationHint").textContent="Address lookup failed just now. You can still pan the map or use your location.";}\n    finally{btn.disabled=false;btn.textContent="Find";}\n  }''')
]

changed = False
for old, new in replacements:
    if new in s:
        continue
    if old not in s:
        raise SystemExit('Expected app.js block not found; refusing partial patch')
    s = s.replace(old, new, 1)
    changed = True

if changed:
    path.write_text(s, encoding='utf-8')
    print('app.js patched to v1.1')
else:
    print('app.js already at v1.1')
